"""initial schema

Revision ID: 0e57a7119005
Revises: 
Create Date: 2026-04-24 19:41:24.368033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e57a7119005'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('buyer', 'supplier', name='user_role'), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('rfqs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('bid_start_time', sa.DateTime(), nullable=False),
    sa.Column('bid_close_time', sa.DateTime(), nullable=False),
    sa.Column('current_bid_close_time', sa.DateTime(), nullable=False),
    sa.Column('forced_bid_close_time', sa.DateTime(), nullable=False),
    sa.Column('pickup_service_date', sa.DateTime(), nullable=True),
    sa.Column('is_british_auction', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', 'force_closed', name='rfq_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('bid_submitted', 'time_extended', 'auction_closed', 'auction_force_closed', name='activity_event_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('extension_reason', sa.String(length=255), nullable=True),
    sa.Column('new_close_time', sa.DateTime(), nullable=True),
    sa.Column('triggered_by_supplier_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_supplier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auction_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('trigger_window_minutes', sa.Integer(), nullable=False),
    sa.Column('extension_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('extension_trigger_type', sa.Enum('bid_received', 'any_rank_change', 'l1_rank_change', name='extension_trigger_type'), nullable=False),
    sa.Column('max_extensions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfq_id')
    )
    op.create_table('bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('carrier_name', sa.String(length=255), nullable=False),
    sa.Column('freight_charges', sa.Numeric(), nullable=False),
    sa.Column('origin_charges', sa.Numeric(), nullable=True),
    sa.Column('destination_charges', sa.Numeric(), nullable=True),
    sa.Column('total_amount', sa.Numeric(), nullable=False),
    sa.Column('transit_time_days', sa.Integer(), nullable=True),
    sa.Column('quote_validity_date', sa.DateTime(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    op.drop_table('auction_configs')
    op.drop_table('activity_logs')
    op.drop_table('rfqs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
