"""add cascade delete to rfq relations

Revision ID: 97ac170447b6
Revises: 0e57a7119005
Create Date: 2026-04-25 20:53:19.657986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ac170447b6'
down_revision: Union[str, Sequence[str], None] = '0e57a7119005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activity_logs_rfq_id_fkey'), 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'rfqs', ['rfq_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('auction_configs_rfq_id_fkey'), 'auction_configs', type_='foreignkey')
    op.create_foreign_key(None, 'auction_configs', 'rfqs', ['rfq_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('bids_rfq_id_fkey'), 'bids', type_='foreignkey')
    op.create_foreign_key(None, 'bids', 'rfqs', ['rfq_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bids', type_='foreignkey')
    op.create_foreign_key(op.f('bids_rfq_id_fkey'), 'bids', 'rfqs', ['rfq_id'], ['id'])
    op.drop_constraint(None, 'auction_configs', type_='foreignkey')
    op.create_foreign_key(op.f('auction_configs_rfq_id_fkey'), 'auction_configs', 'rfqs', ['rfq_id'], ['id'])
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('activity_logs_rfq_id_fkey'), 'activity_logs', 'rfqs', ['rfq_id'], ['id'])
    # ### end Alembic commands ###
